name: Frontend Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  frontend-lint:
    name: Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: starter/frontend/.nvmrc

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: starter/frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run lint
        working-directory: starter/frontend
        run: npm run lint

  frontend-test:
    name: Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: starter/frontend/.nvmrc

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: starter/frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run tests
        working-directory: starter/frontend
        run: CI=true npm test -- --watchAll=false

  frontend-build:
    name: Build Frontend
    needs:
      - frontend-lint
      - frontend-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: starter/frontend/.nvmrc

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: starter/frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Build frontend
        working-directory: starter/frontend
        run: npm run build